server:
  port: 9000
spring:
  application:
    name: board-test-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/inf-article
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace